name: Wheel packaging tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build
      - name: Build wheel
        run: |
          python -m build --wheel
      - name: Fetch dependencies
        run: |
          python -m pip wheel --wheel-dir=dist dist/*.whl
      - name: Install wheel
        run: |
          python -m pip install -f dist --no-index gurobipy-pandas
      - name: Test import
        run: |
          python -c "import gurobipy_pandas"
      - name: Run unittest
        run: |
          python -m unittest -b
